version: "3.8"
services:
  devenv:
    container_name: wasmcloud-dev
    image: wasmcloud-dev:latest
    volumes:
      - ./.cargo:/cargo
      - ./projects:/usr/src/development
    links:
      - redis
      - nats
  redis:
    image: redis
  nats:
    image: nats:latest
